<?php
namespace AtlasShipping\Shipping;
use AtlasShipping\Identities;
use AtlasShipping\Migrator;
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Service {
 private $requests; private $stops; private $items; private $snapshots; private $wpdb;
 public function __construct($wpdb=null){$this->wpdb=$wpdb?:$GLOBALS['wpdb'];$this->requests=new RequestRepository($this->wpdb);$this->stops=new StopRepository($this->wpdb);$this->items=new ItemRepository($this->wpdb);$this->snapshots=new SnapshotRepository($this->wpdb);}
 public function create_draft($data,$actor_id,$stops=array(),$items=array()){$actor=$this->actor($actor_id);if(is_wp_error($actor))return$actor;$owner=absint($actor_id);$data=$this->request_data($data);if(is_wp_error($data))return$data;$data=array_merge($data,array('owner_identity_id'=>$owner,'created_by_identity_id'=>$actor_id,'updated_by_identity_id'=>$actor_id,'status'=>'draft'));$this->begin();$request=$this->requests->create($data);if(is_wp_error($request))return$this->rollback($request);foreach($stops as$stop){$result=$this->add_stop($request->id(),$stop,$actor_id,false);if(is_wp_error($result))return$this->rollback($result);}foreach($items as$item){$result=$this->add_item($request->id(),$item,$actor_id,false);if(is_wp_error($result))return$this->rollback($result);}$this->commit();$this->activity('request_created','A shipping request draft was created.',$request->id(),$actor_id,array('public_id'=>$request->get('public_id')));return$this->load($request->id());}
 public function load($id,$include_archived=false){$request=$this->requests->find($id,$include_archived);if(!$request)return new \WP_Error('atlas_request_not_found',__('The shipping request was not found.','atlas-shipping'));$request->stops=$this->stops->for_request($id);$request->items=$this->items->for_request($id);$request->snapshots=$this->snapshots->for_request($id);return$request;}
 public function resume($actor){$valid=$this->actor($actor);if(is_wp_error($valid))return$valid;$r=$this->requests->latest_draft_for_owner($actor);return$r?$this->load($r->id()):null;}
 public function load_for_owner($public,$actor){$r=$this->requests->find_by_public_id($public);return(!$r||absint($r->get('owner_identity_id'))!==absint($actor))?new \WP_Error('atlas_request_forbidden',__('This request is not editable by the current identity.','atlas-shipping')):$this->load($r->id());}
 public function update_request($id,$data,$actor_id,$expected_version,$log=true){$actor=$this->actor($actor_id);if(is_wp_error($actor))return$actor;$request=$this->editable($id,$actor_id);if(is_wp_error($request))return$request;$data=$this->request_data($data,false);if(is_wp_error($data))return$data;$data['updated_by_identity_id']=absint($actor_id);if(!$this->requests->update($id,$data,$expected_version))return new \WP_Error('atlas_request_conflict',__('The shipping request changed before this update could be saved.','atlas-shipping'));if($log)$this->activity('request_updated','A shipping request was updated.',$id,$actor_id);return$this->load($id);}
 public function submit($id,$actor,$version){$request=$this->editable($id,$actor);if(is_wp_error($request))return$request;$aggregate=$this->load($id);$errors=array();if(!trim($request->get('project_id'))&&!trim($request->get('project_name')))$errors['project_id']=__('Enter a project ID or project/site name.','atlas-shipping');$pickup=false;$delivery=false;foreach($aggregate->stops as$s){if(in_array($s->get('stop_type'),array('pickup','delivery'),true)&&(!trim($s->get('address_line_1'))||!trim($s->get('city'))||!trim($s->get('region'))||!trim($s->get('postal_code'))))$errors['stops']=__('Pickup and delivery stops require street, city, region, and postal code.','atlas-shipping');$pickup=$pickup||'pickup'===$s->get('stop_type');$delivery=$delivery||'delivery'===$s->get('stop_type');}if(!$pickup)$errors['pickup']=__('Add a pickup stop.','atlas-shipping');if(!$delivery)$errors['delivery']=__('Add a delivery stop.','atlas-shipping');if(!$aggregate->items)$errors['items']=__('Add at least one shipment item.','atlas-shipping');foreach($aggregate->items as$i)if((float)$i->get('quantity')<=0||!trim($i->get('description')))$errors['items']=__('Every item needs a positive quantity and description.','atlas-shipping');if($errors)return new \WP_Error('atlas_submission_invalid',__('Review the highlighted request details.','atlas-shipping'),array('fields'=>$errors));$result=$this->update_request($id,array('status'=>'submitted','submitted_at'=>gmdate('Y-m-d H:i:s')),$actor,$version,false);if(is_wp_error($result))return$result;$this->activity('request_submitted','A shipping request was submitted.',$id,$actor,array('public_id'=>$request->get('public_id')));return$result;}
 public function archive($id,$actor_id){$actor=$this->actor($actor_id);if(is_wp_error($actor))return$actor;if(!$this->requests->find($id))return$this->parent_error();if(!$this->requests->archive($id,$actor_id))return new \WP_Error('atlas_request_archive_failed',__('The shipping request could not be archived.','atlas-shipping'));$this->activity('request_archived','A shipping request was archived.',$id,$actor_id);return true;}
 public function add_stop($request,$data,$actor,$log=true){$valid=$this->mutation_context($request,$actor);if(is_wp_error($valid))return$valid;$data=$this->stop_data($data);if(is_wp_error($data))return$data;$data['request_id']=absint($request);$result=$this->stops->create($data);if($log&&!is_wp_error($result))$this->activity('stop_created','A shipping stop was created.',$request,$actor,array('sequence'=>$data['sequence_no']));return$result;}
 public function update_stop($id,$data,$actor,$log=true){$valid=$this->actor($actor);if(is_wp_error($valid))return$valid;$existing=$this->stops->find($id);if(!$existing)return new \WP_Error('atlas_stop_not_found',__('The shipping stop was not found.','atlas-shipping'));$valid=$this->editable($existing->get('request_id'),$actor);if(is_wp_error($valid))return$valid;$data=$this->stop_data($data);if(is_wp_error($data))return$data;if(!$this->stops->resequence($id,$existing->get('request_id'),$data['sequence_no']))return new \WP_Error('atlas_stop_reorder_failed',__('The shipping stops could not be reordered.','atlas-shipping'));unset($data['sequence_no']);$ok=$this->stops->update($id,$data);if(!$ok)return new \WP_Error('atlas_stop_update_failed',__('The shipping stop could not be updated.','atlas-shipping'));if($log)$this->activity('stop_updated','A shipping stop was updated.',$existing->get('request_id'),$actor);return true;}
 public function remove_stop($id,$actor){$valid=$this->actor($actor);if(is_wp_error($valid))return$valid;$existing=$this->stops->find($id);if(!$existing)return new \WP_Error('atlas_stop_not_found',__('The shipping stop was not found.','atlas-shipping'));$valid=$this->editable($existing->get('request_id'),$actor);if(is_wp_error($valid))return$valid;$ok=$this->stops->delete($id);if($ok)$this->activity('stop_removed','A shipping stop was removed.',$existing->get('request_id'),$actor);return$ok;}
 public function add_item($request,$data,$actor,$log=true){$valid=$this->mutation_context($request,$actor);if(is_wp_error($valid))return$valid;$data=$this->item_data($data);if(is_wp_error($data))return$data;$data['request_id']=absint($request);$result=$this->items->create($data);if($log&&!is_wp_error($result))$this->activity('item_created','A shipment item was created.',$request,$actor,array('sequence'=>$data['sequence_no']));return$result;}
 public function update_item($id,$data,$actor,$log=true){$valid=$this->actor($actor);if(is_wp_error($valid))return$valid;$existing=$this->items->find($id);if(!$existing)return new \WP_Error('atlas_item_not_found',__('The shipment item was not found.','atlas-shipping'));$valid=$this->editable($existing->get('request_id'),$actor);if(is_wp_error($valid))return$valid;$data=$this->item_data($data);if(is_wp_error($data))return$data;if(!$this->items->resequence($id,$existing->get('request_id'),$data['sequence_no']))return new \WP_Error('atlas_item_reorder_failed',__('The shipment items could not be reordered.','atlas-shipping'));unset($data['sequence_no']);$ok=$this->items->update($id,$data);if(!$ok)return new \WP_Error('atlas_item_update_failed',__('The shipment item could not be updated.','atlas-shipping'));if($log)$this->activity('item_updated','A shipment item was updated.',$existing->get('request_id'),$actor);return true;}
 public function remove_item($id,$actor){$valid=$this->actor($actor);if(is_wp_error($valid))return$valid;$existing=$this->items->find($id);if(!$existing)return new \WP_Error('atlas_item_not_found',__('The shipment item was not found.','atlas-shipping'));$valid=$this->editable($existing->get('request_id'),$actor);if(is_wp_error($valid))return$valid;$ok=$this->items->delete($id);if($ok)$this->activity('item_removed','A shipment item was removed.',$existing->get('request_id'),$actor);return$ok;}
 public function create_snapshot($request_id,$type,$actor_id,$reason='',$parent=null){$valid=$this->mutation_context($request_id,$actor_id);if(is_wp_error($valid))return$valid;$aggregate=$this->load($request_id);if(is_wp_error($aggregate))return$aggregate;$payload=array('request'=>$aggregate->to_array(),'stops'=>array_map(fn($v)=>$v->to_array(),$aggregate->stops),'items'=>array_map(fn($v)=>$v->to_array(),$aggregate->items));$content=wp_json_encode($payload,JSON_UNESCAPED_SLASHES);for($attempt=0;$attempt<3;$attempt++){$this->begin();$number=$this->snapshots->next_number_for_update($request_id);$snapshot=$this->snapshots->create(array('request_id'=>absint($request_id),'snapshot_no'=>$number,'snapshot_type'=>sanitize_key($type),'created_by_identity_id'=>absint($actor_id),'parent_snapshot_id'=>$parent?absint($parent):null,'reason'=>sanitize_textarea_field($reason),'content'=>$content,'content_hash'=>hash('sha256',$content)));if(!is_wp_error($snapshot)){$this->commit();$this->activity('snapshot_created','An immutable shipping request snapshot was created.',$request_id,$actor_id,array('snapshot_no'=>$number,'content_hash'=>$snapshot->get('content_hash')));return$snapshot;}$this->wpdb->query('ROLLBACK');}return new \WP_Error('atlas_snapshot_allocation_failed',__('A unique snapshot number could not be allocated.','atlas-shipping'));}
 private function actor($id){$id=absint($id);return$id&&Identities::find($id)?true:new \WP_Error('atlas_actor_identity_invalid',__('A valid acting application identity is required.','atlas-shipping'));}
 private function editable($id,$actor){$r=$this->requests->find($id);if(!$r)return$this->parent_error();if(absint($r->get('owner_identity_id'))!==absint($actor))return new \WP_Error('atlas_request_forbidden',__('This request is not editable by the current identity.','atlas-shipping'));if(!in_array($r->get('status'),array('draft','submitted'),true))return new \WP_Error('atlas_request_locked',__('This request can no longer be edited.','atlas-shipping'));return$r;}
 private function mutation_context($request,$actor){$valid=$this->actor($actor);if(is_wp_error($valid))return$valid;$r=$this->editable($request,$actor);return is_wp_error($r)?$r:true;}
 private function parent_error(){return new \WP_Error('atlas_request_parent_invalid',__('The active parent shipping request was not found.','atlas-shipping'));}
 private function activity($type,$summary,$request,$actor,$metadata=array()){$metadata['actor_identity_id']=absint($actor);return Migrator::log_activity($type,$summary,$metadata,'shipping_request',$request);}
 private function request_data($d,$default_status=true){$out=array();if($default_status||array_key_exists('status',$d)){$status=sanitize_key($d['status']??'draft');if(!in_array($status,Request::STATUSES,true))return new \WP_Error('atlas_request_status_invalid',__('The request status is invalid.','atlas-shipping'));$out['status']=$status;}foreach(array('project_id','internal_id','client','project_name','delivery_date_firmness','preferred_equipment')as$k)if(array_key_exists($k,$d))$out[$k]=sanitize_text_field($d[$k]);foreach(array('requested_ship_date','required_delivery_date')as$k)if(array_key_exists($k,$d)){$v=$d[$k];if($v&&'Y-m-d'!==date('Y-m-d',strtotime($v)))return new \WP_Error('atlas_request_date_invalid',__('A shipping date is invalid.','atlas-shipping'));$out[$k]=$v?:null;}foreach(array('notes','transportation_comment')as$k)if(array_key_exists($k,$d))$out[$k]=sanitize_textarea_field($d[$k]);foreach(array('client_requested','service_load_pickup','service_unload_delivery','third_party_loading','third_party_unloading')as$k)if(array_key_exists($k,$d))$out[$k]=empty($d[$k])?0:1;if(array_key_exists('submitted_at',$d))$out['submitted_at']=$d['submitted_at'];return$out;}
 private function stop_data($d){$type=sanitize_key($d['stop_type']??'');$seq=absint($d['sequence_no']??0);if(!in_array($type,Stop::TYPES,true)||$seq<1)return new \WP_Error('atlas_stop_invalid',__('Stop type and sequence are required.','atlas-shipping'));$out=array('sequence_no'=>$seq,'stop_type'=>$type);foreach(array('site_name','address_line_1','address_line_2','city','region','postal_code','country','contact_name','contact_phone','handling_responsibility','equipment_notes','instructions')as$k)$out[$k]=in_array($k,array('equipment_notes','instructions'),true)?sanitize_textarea_field($d[$k]??''):sanitize_text_field($d[$k]??'');$email=sanitize_email($d['contact_email']??'');if($email&&!is_email($email))return new \WP_Error('atlas_stop_email_invalid',__('The stop contact email is invalid.','atlas-shipping'));$out['contact_email']=$email?:null;foreach(array('window_start','window_end')as$k){$out[$k]=$this->datetime($d[$k]??null);if(is_wp_error($out[$k]))return$out[$k];}if($out['window_start']&&$out['window_end']&&$out['window_start']>$out['window_end'])return new \WP_Error('atlas_stop_window_reversed',__('The stop window end must not precede its start.','atlas-shipping'));foreach(array('appointment_required','dock_available','forklift_available')as$k)$out[$k]=empty($d[$k])?0:1;return$out;}
 private function datetime($value){if(null===$value||''===$value)return null;$value=sanitize_text_field($value);$zone=new \DateTimeZone('UTC');$date=\DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$value,$zone);$errors=\DateTimeImmutable::getLastErrors();if(!$date||(false!==$errors&&($errors['warning_count']||$errors['error_count']))||$date->format('Y-m-d H:i:s')!==$value)return new \WP_Error('atlas_stop_datetime_invalid',__('A stop window datetime is invalid. Use UTC YYYY-MM-DD HH:MM:SS.','atlas-shipping'));return$date->format('Y-m-d H:i:s');}
 private function item_data($d){$seq=absint($d['sequence_no']??0);$qty=(float)($d['quantity']??0);if($seq<1||$qty<=0)return new \WP_Error('atlas_item_invalid',__('Item sequence and positive quantity are required.','atlas-shipping'));$out=array('sequence_no'=>$seq,'quantity'=>$qty,'description'=>sanitize_text_field($d['description']??''));foreach(array('length','width','height','weight')as$k){$v=isset($d[$k])?(float)$d[$k]:null;if(null!==$v&&$v<0)return new \WP_Error('atlas_item_measurement_invalid',__('Item measurements cannot be negative.','atlas-shipping'));$out[$k]=$v;}foreach(array('dimension_unit','weight_basis','weight_unit','packaging_type')as$k)$out[$k]=sanitize_key($d[$k]??'');foreach(array('stackable','fork_pockets','weather_sensitive')as$k)$out[$k]=empty($d[$k])?0:1;$out['special_handling']=sanitize_textarea_field($d['special_handling']??'');return$out;}
 private function begin(){$this->wpdb->query('START TRANSACTION');}private function commit(){$this->wpdb->query('COMMIT');}private function rollback($error){$this->wpdb->query('ROLLBACK');return$error;}
}
