<?php
namespace AtlasShipping\Shipping;
if ( ! defined( 'ABSPATH' ) ) { exit; }
abstract class Repository { protected $wpdb; protected $table; public function __construct($wpdb=null){$this->wpdb=$wpdb?:$GLOBALS['wpdb'];} protected function now(){return gmdate('Y-m-d H:i:s');} }
final class RequestRepository extends Repository {
 public function __construct($wpdb=null){parent::__construct($wpdb);$this->table=$this->wpdb->prefix.'atlas_shipping_requests';}
 public function find($id,$include_archived=false){$sql='SELECT * FROM '.$this->table.' WHERE id=%d'.($include_archived?'':' AND archived_at IS NULL');$row=$this->wpdb->get_row($this->wpdb->prepare($sql,absint($id)));return $row?new Request($row):null;}
 public function find_by_public_id($public_id,$include_archived=false){$sql='SELECT * FROM '.$this->table.' WHERE public_id=%s'.($include_archived?'':' AND archived_at IS NULL');$row=$this->wpdb->get_row($this->wpdb->prepare($sql,sanitize_text_field($public_id)));return $row?new Request($row):null;}
 public function latest_draft_for_owner($owner){$row=$this->wpdb->get_row($this->wpdb->prepare("SELECT * FROM {$this->table} WHERE owner_identity_id=%d AND status='draft' AND archived_at IS NULL ORDER BY updated_at DESC,id DESC LIMIT 1",absint($owner)));return$row?new Request($row):null;}
 public function listing($args){$where=array('r.archived_at IS NULL');$values=array();if(!empty($args['owner'])){$where[]='r.owner_identity_id=%d';$values[]=absint($args['owner']);}if(!empty($args['status'])){$where[]='r.status=%s';$values[]=sanitize_key($args['status']);}if(!empty($args['search'])){$like='%'.$this->wpdb->esc_like($args['search']).'%';$where[]='(r.public_id LIKE %s OR r.project_id LIKE %s OR r.project_name LIKE %s OR r.client LIKE %s)';array_push($values,$like,$like,$like,$like);}$past='past'===($args['view']??'');$past_status="('complete','cancelled','delivery_verified')";$where[]=$past?"(r.status IN $past_status OR COALESCE(r.required_delivery_date,r.requested_ship_date)<UTC_DATE())":"(r.status NOT IN $past_status AND (COALESCE(r.required_delivery_date,r.requested_ship_date)>=UTC_DATE() OR COALESCE(r.required_delivery_date,r.requested_ship_date) IS NULL))";$sorts=array('relevant_date'=>'COALESCE(r.required_delivery_date,r.requested_ship_date)','created'=>'r.created_at','updated'=>'r.updated_at','status'=>'r.status','owner'=>'i.full_name');$key=$args['sort']??'relevant_date';$sort=$sorts[$key]??$sorts['relevant_date'];$dir='desc'===strtolower($args['direction']??'')?'DESC':'ASC';if($past&&'relevant_date'===$key)$dir='DESC';$page=max(1,absint($args['page']??1));$size=min(50,max(1,absint($args['per_page']??25)));$base=" FROM {$this->table} r JOIN {$this->wpdb->prefix}atlas_shipping_identities i ON i.id=r.owner_identity_id WHERE ".implode(' AND ',$where);$count='SELECT COUNT(*)'.$base;$total=(int)$this->wpdb->get_var($values?$this->wpdb->prepare($count,$values):$count);$select="SELECT r.public_id,r.owner_identity_id,i.full_name owner_name,r.status,r.project_id,r.project_name,r.client,r.requested_ship_date,r.required_delivery_date,r.created_at,r.submitted_at,r.updated_at,(SELECT CONCAT_WS(', ',s.site_name,s.city,s.region) FROM {$this->wpdb->prefix}atlas_shipping_stops s WHERE s.request_id=r.id AND s.stop_type='pickup' ORDER BY s.sequence_no LIMIT 1) pickup,(SELECT CONCAT_WS(', ',s.site_name,s.city,s.region) FROM {$this->wpdb->prefix}atlas_shipping_stops s WHERE s.request_id=r.id AND s.stop_type='delivery' ORDER BY s.sequence_no LIMIT 1) delivery".$base." ORDER BY ($sort IS NULL),$sort $dir,r.id $dir LIMIT %d OFFSET %d";$rows=$this->wpdb->get_results($this->wpdb->prepare($select,array_merge($values,array($size,($page-1)*$size))),ARRAY_A);return array('rows'=>$rows,'total'=>$total,'page'=>$page,'per_page'=>$size,'pages'=>(int)ceil($total/$size));}
 public function create($data){$now=$this->now();$row=array_merge(array('public_id'=>null,'status'=>'draft','project_id'=>'','client'=>'','project_name'=>'','delivery_date_firmness'=>'unknown','client_requested'=>0,'row_version'=>1,'created_at'=>$now,'updated_at'=>$now),$data);$ok=$this->wpdb->insert($this->table,$row);if(false===$ok)return new \WP_Error('atlas_request_create_failed',__('The shipping request could not be created.','atlas-shipping'));$id=(int)$this->wpdb->insert_id;$public='AS-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);$updated=$this->wpdb->query($this->wpdb->prepare('UPDATE '.$this->table.' SET public_id=%s WHERE id=%d AND public_id IS NULL',$public,$id));return 1===$updated?$this->find($id,true):new \WP_Error('atlas_request_public_id_failed',__('The request identifier could not be assigned.','atlas-shipping'));}
 public function update($id,$data,$expected_version){$data['updated_at']=$this->now();$sets=array();$values=array();foreach($data as$key=>$value){if(null===$value){$sets[]=$key.'=NULL';}else{$sets[]=$key.'=%s';$values[]=$value;}}$sets[]='row_version=row_version+1';$values[]=absint($id);$values[]=absint($expected_version);return 1===$this->wpdb->query($this->wpdb->prepare('UPDATE '.$this->table.' SET '.implode(',',$sets).' WHERE id=%d AND row_version=%d AND archived_at IS NULL',$values));}
 public function archive($id,$actor){return 1===$this->wpdb->query($this->wpdb->prepare('UPDATE '.$this->table.' SET archived_at=%s,updated_at=%s,updated_by_identity_id=%d,row_version=row_version+1 WHERE id=%d AND archived_at IS NULL',$this->now(),$this->now(),absint($actor),absint($id)));}
}
abstract class OrderedRepository extends Repository {
 protected $model;
 public function for_request($request){$rows=$this->wpdb->get_results($this->wpdb->prepare('SELECT * FROM '.$this->table.' WHERE request_id=%d ORDER BY sequence_no ASC,id ASC',absint($request)));return array_map(function($r){$c=$this->model;return new $c($r);},$rows);}
 public function find($id){$r=$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.$this->table.' WHERE id=%d',absint($id)));$c=$this->model;return$r?new $c($r):null;}
 public function create($data){$now=$this->now();$data['created_at']=$now;$data['updated_at']=$now;$ok=$this->wpdb->insert($this->table,$data);return false===$ok?new \WP_Error('atlas_relationship_create_failed',__('The related shipping record could not be created.','atlas-shipping')):$this->find($this->wpdb->insert_id);}
 public function update($id,$data){$data['updated_at']=$this->now();return false!==$this->wpdb->update($this->table,$data,array('id'=>absint($id)));}
 public function delete($id){return false!==$this->wpdb->delete($this->table,array('id'=>absint($id)),array('%d'));}
 public function resequence($id,$request,$sequence){$id=absint($id);$request=absint($request);$sequence=absint($sequence);$current=$this->find($id);if(!$current||absint($current->get('request_id'))!==$request)return false;$old=absint($current->get('sequence_no'));if($old===$sequence)return true;$other=(int)$this->wpdb->get_var($this->wpdb->prepare('SELECT id FROM '.$this->table.' WHERE request_id=%d AND sequence_no=%d',$request,$sequence));if($other&&false===$this->wpdb->update($this->table,array('sequence_no'=>1000000000+$other),array('id'=>$other)))return false;if(false===$this->wpdb->update($this->table,array('sequence_no'=>$sequence),array('id'=>$id)))return false;if($other&&false===$this->wpdb->update($this->table,array('sequence_no'=>$old),array('id'=>$other)))return false;return true;}
}
final class StopRepository extends OrderedRepository {public function __construct($wpdb=null){parent::__construct($wpdb);$this->table=$this->wpdb->prefix.'atlas_shipping_stops';$this->model=Stop::class;}}
final class ItemRepository extends OrderedRepository {public function __construct($wpdb=null){parent::__construct($wpdb);$this->table=$this->wpdb->prefix.'atlas_shipping_items';$this->model=Item::class;}}
final class SnapshotRepository extends Repository {
 public function __construct($wpdb=null){parent::__construct($wpdb);$this->table=$this->wpdb->prefix.'atlas_shipping_snapshots';}
 public function for_request($request){$rows=$this->wpdb->get_results($this->wpdb->prepare('SELECT * FROM '.$this->table.' WHERE request_id=%d ORDER BY snapshot_no ASC',absint($request)));return array_map(fn($r)=>new Snapshot($r),$rows);}
 public function next_number_for_update($request){return 1+(int)$this->wpdb->get_var($this->wpdb->prepare('SELECT COALESCE(MAX(snapshot_no),0) FROM '.$this->table.' WHERE request_id=%d FOR UPDATE',absint($request)));}
 public function create($data){$data['created_at']=$this->now();$ok=$this->wpdb->insert($this->table,$data);if(false===$ok)return new \WP_Error('atlas_snapshot_create_failed',__('The immutable snapshot could not be stored.','atlas-shipping'));$row=$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.$this->table.' WHERE id=%d',$this->wpdb->insert_id));return new Snapshot($row);}
}
final class HandoffRepository extends Repository {
 public function __construct($wpdb=null){parent::__construct($wpdb);$this->table=$this->wpdb->prefix.'atlas_shipping_handoffs';}
 public function find_for_request($request){return$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.$this->table.' WHERE request_id=%d',absint($request)),ARRAY_A);}
 public function save($request,$actor,$data){$now=$this->now();$row=array('request_id'=>absint($request),'coordinator_identity_id'=>absint($actor),'final_equipment'=>sanitize_key($data['final_equipment']??''),'other_equipment'=>sanitize_text_field($data['other_equipment']??''),'coordinator_notes'=>sanitize_textarea_field($data['coordinator_notes']??''),'load_pickup'=>empty($data['load_pickup'])?0:1,'unload_delivery'=>empty($data['unload_delivery'])?0:1,'updated_at'=>$now);$existing=$this->find_for_request($request);if($existing)return false!==$this->wpdb->update($this->table,$row,array('request_id'=>absint($request)));$row['created_at']=$now;return false!==$this->wpdb->insert($this->table,$row);}
 public function mark_sent($request,$snapshot){return false!==$this->wpdb->update($this->table,array('snapshot_id'=>absint($snapshot),'sent_at'=>$this->now(),'updated_at'=>$this->now()),array('request_id'=>absint($request)));}
}
final class ShipperResponseRepository extends Repository {
 public function __construct($wpdb=null){parent::__construct($wpdb);$this->table=$this->wpdb->prefix.'atlas_shipping_shipper_responses';}
 public function find_for_request($request){return$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.$this->table.' WHERE request_id=%d',absint($request)),ARRAY_A);}
 public function save($request,$actor,$data,$final=false){$now=$this->now();$row=array_merge($data,array('request_id'=>absint($request),'coordinator_identity_id'=>absint($actor),'response_status'=>$final?'confirmed':'draft','updated_at'=>$now));if($final)$row['confirmed_at']=$now;$existing=$this->find_for_request($request);if($existing)return false!==$this->wpdb->update($this->table,$row,array('request_id'=>absint($request)));$row['created_at']=$now;return false!==$this->wpdb->insert($this->table,$row);}
}
