<?php
namespace AtlasShipping\Shipping;
use AtlasShipping\Identities;
use AtlasShipping\Migrator;
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Service {
 private $requests; private $stops; private $items; private $snapshots; private $wpdb;
 public function __construct($wpdb=null){$this->wpdb=$wpdb?:$GLOBALS['wpdb'];$this->requests=new RequestRepository($this->wpdb);$this->stops=new StopRepository($this->wpdb);$this->items=new ItemRepository($this->wpdb);$this->snapshots=new SnapshotRepository($this->wpdb);}
 public function create_draft($data,$actor_id,$stops=array(),$items=array()){
  $actor_id=absint($actor_id);$owner=absint($data['owner_identity_id']??$actor_id);
  if(!$actor_id||!Identities::find($actor_id)||!$owner||!Identities::find($owner))return new \WP_Error('atlas_request_identity_invalid',__('A valid application identity is required.','atlas-shipping'));
  $data=$this->request_data($data);if(is_wp_error($data))return$data;$data=array_merge($data,array('owner_identity_id'=>$owner,'created_by_identity_id'=>$actor_id,'updated_by_identity_id'=>$actor_id,'status'=>'draft'));
  $this->begin();$request=$this->requests->create($data);if(is_wp_error($request))return$this->rollback($request);
  foreach($stops as$stop){$result=$this->add_stop($request->id(),$stop,$actor_id,false);if(is_wp_error($result))return$this->rollback($result);}
  foreach($items as$item){$result=$this->add_item($request->id(),$item,$actor_id,false);if(is_wp_error($result))return$this->rollback($result);}
  $this->commit();Migrator::log_activity('request_created','A shipping request draft was created.',array('public_id'=>$request->get('public_id')),'shipping_request',$request->id());return$this->load($request->id());
 }
 public function load($id,$include_archived=false){$request=$this->requests->find($id,$include_archived);if(!$request)return new \WP_Error('atlas_request_not_found',__('The shipping request was not found.','atlas-shipping'));$request->stops=$this->stops->for_request($id);$request->items=$this->items->for_request($id);$request->snapshots=$this->snapshots->for_request($id);return$request;}
 public function update_request($id,$data,$actor_id,$expected_version){$data=$this->request_data($data,false);if(is_wp_error($data))return$data;$data['updated_by_identity_id']=absint($actor_id);if(!$this->requests->update($id,$data,$expected_version))return new \WP_Error('atlas_request_conflict',__('The shipping request changed before this update could be saved.','atlas-shipping'));Migrator::log_activity('request_updated','A shipping request was updated.',array('actor_identity_id'=>absint($actor_id)),'shipping_request',$id);return$this->load($id);}
 public function archive($id,$actor_id){if(!$this->requests->archive($id,$actor_id))return new \WP_Error('atlas_request_archive_failed',__('The shipping request could not be archived.','atlas-shipping'));Migrator::log_activity('request_archived','A shipping request was archived.',array(),'shipping_request',$id);return true;}
 public function add_stop($request,$data,$actor,$log=true){$data=$this->stop_data($data);if(is_wp_error($data))return$data;$data['request_id']=absint($request);$result=$this->stops->create($data);if($log&&!is_wp_error($result))Migrator::log_activity('stop_created','A shipping stop was created.',array('sequence'=>$data['sequence_no']),'shipping_request',$request);return$result;}
 public function update_stop($id,$data,$actor){$existing=$this->stops->find($id);if(!$existing)return new \WP_Error('atlas_stop_not_found',__('The shipping stop was not found.','atlas-shipping'));$data=$this->stop_data($data);if(is_wp_error($data))return$data;$ok=$this->stops->update($id,$data);if($ok)Migrator::log_activity('stop_updated','A shipping stop was updated.',array(),'shipping_request',$existing->get('request_id'));return$ok;}
 public function remove_stop($id,$actor){$existing=$this->stops->find($id);if(!$existing)return false;$ok=$this->stops->delete($id);if($ok)Migrator::log_activity('stop_removed','A shipping stop was removed.',array(),'shipping_request',$existing->get('request_id'));return$ok;}
 public function add_item($request,$data,$actor,$log=true){$data=$this->item_data($data);if(is_wp_error($data))return$data;$data['request_id']=absint($request);$result=$this->items->create($data);if($log&&!is_wp_error($result))Migrator::log_activity('item_created','A shipment item was created.',array('sequence'=>$data['sequence_no']),'shipping_request',$request);return$result;}
 public function update_item($id,$data,$actor){$existing=$this->items->find($id);if(!$existing)return new \WP_Error('atlas_item_not_found',__('The shipment item was not found.','atlas-shipping'));$data=$this->item_data($data);if(is_wp_error($data))return$data;$ok=$this->items->update($id,$data);if($ok)Migrator::log_activity('item_updated','A shipment item was updated.',array(),'shipping_request',$existing->get('request_id'));return$ok;}
 public function remove_item($id,$actor){$existing=$this->items->find($id);if(!$existing)return false;$ok=$this->items->delete($id);if($ok)Migrator::log_activity('item_removed','A shipment item was removed.',array(),'shipping_request',$existing->get('request_id'));return$ok;}
 public function create_snapshot($request_id,$type,$actor_id,$reason='',$parent=null){$aggregate=$this->load($request_id,true);if(is_wp_error($aggregate))return$aggregate;$prior=$this->snapshots->for_request($request_id);$payload=array('request'=>$aggregate->to_array(),'stops'=>array_map(fn($v)=>$v->to_array(),$aggregate->stops),'items'=>array_map(fn($v)=>$v->to_array(),$aggregate->items));$content=wp_json_encode($payload,JSON_UNESCAPED_SLASHES);$snapshot=$this->snapshots->create(array('request_id'=>absint($request_id),'snapshot_no'=>count($prior)+1,'snapshot_type'=>sanitize_key($type),'created_by_identity_id'=>absint($actor_id),'parent_snapshot_id'=>$parent?absint($parent):null,'reason'=>sanitize_textarea_field($reason),'content'=>$content,'content_hash'=>hash('sha256',$content)));if(!is_wp_error($snapshot))Migrator::log_activity('snapshot_created','An immutable shipping request snapshot was created.',array('snapshot_no'=>$snapshot->get('snapshot_no'),'content_hash'=>$snapshot->get('content_hash')),'shipping_request',$request_id);return$snapshot;}
 private function request_data($d,$default_status=true){$out=array();if($default_status||array_key_exists('status',$d)){$status=sanitize_key($d['status']??'draft');if(!in_array($status,Request::STATUSES,true))return new \WP_Error('atlas_request_status_invalid',__('The request status is invalid.','atlas-shipping'));$out['status']=$status;}foreach(array('project_id','internal_id','client','project_name','delivery_date_firmness')as$k)if(array_key_exists($k,$d))$out[$k]=sanitize_text_field($d[$k]);foreach(array('requested_ship_date','required_delivery_date')as$k)if(array_key_exists($k,$d)){$v=$d[$k];if($v&&'Y-m-d'!==date('Y-m-d',strtotime($v)))return new \WP_Error('atlas_request_date_invalid',__('A shipping date is invalid.','atlas-shipping'));$out[$k]=$v?:null;}if(array_key_exists('notes',$d))$out['notes']=sanitize_textarea_field($d['notes']);if(array_key_exists('client_requested',$d))$out['client_requested']=empty($d['client_requested'])?0:1;if(array_key_exists('freight_cost',$d)){$v=(float)$d['freight_cost'];if($v<0)return new \WP_Error('atlas_freight_cost_invalid',__('Freight cost cannot be negative.','atlas-shipping'));$out['freight_cost']=$v;}return$out;}
 private function stop_data($d){$type=sanitize_key($d['stop_type']??'');$seq=absint($d['sequence_no']??0);if(!in_array($type,Stop::TYPES,true)||$seq<1)return new \WP_Error('atlas_stop_invalid',__('Stop type and sequence are required.','atlas-shipping'));$out=array('sequence_no'=>$seq,'stop_type'=>$type);foreach(array('site_name','address_line_1','address_line_2','city','region','postal_code','country','contact_name','contact_phone','handling_responsibility','equipment_notes','instructions')as$k)$out[$k]=in_array($k,array('equipment_notes','instructions'),true)?sanitize_textarea_field($d[$k]??''):sanitize_text_field($d[$k]??'');$email=sanitize_email($d['contact_email']??'');if($email&&!is_email($email))return new \WP_Error('atlas_stop_email_invalid',__('The stop contact email is invalid.','atlas-shipping'));$out['contact_email']=$email?:null;foreach(array('window_start','window_end')as$k)$out[$k]=empty($d[$k])?null:sanitize_text_field($d[$k]);foreach(array('appointment_required','dock_available','forklift_available')as$k)$out[$k]=empty($d[$k])?0:1;return$out;}
 private function item_data($d){$seq=absint($d['sequence_no']??0);$qty=(float)($d['quantity']??0);if($seq<1||$qty<=0)return new \WP_Error('atlas_item_invalid',__('Item sequence and positive quantity are required.','atlas-shipping'));$out=array('sequence_no'=>$seq,'quantity'=>$qty,'description'=>sanitize_text_field($d['description']??''));foreach(array('length','width','height','weight')as$k){$v=isset($d[$k])?(float)$d[$k]:null;if(null!==$v&&$v<0)return new \WP_Error('atlas_item_measurement_invalid',__('Item measurements cannot be negative.','atlas-shipping'));$out[$k]=$v;}foreach(array('dimension_unit','weight_basis','weight_unit','packaging_type')as$k)$out[$k]=sanitize_key($d[$k]??'');foreach(array('stackable','fork_pockets','weather_sensitive')as$k)$out[$k]=empty($d[$k])?0:1;$out['special_handling']=sanitize_textarea_field($d['special_handling']??'');return$out;}
 private function begin(){$this->wpdb->query('START TRANSACTION');}private function commit(){$this->wpdb->query('COMMIT');}private function rollback($error){$this->wpdb->query('ROLLBACK');return$error;}
}
