<?php
require 'C:/Users/govin/Local Sites/atlas/app/public/wp-load.php';use AtlasShipping\Shipping\Service;
function m3check($v,$c){if(!$v)throw new RuntimeException($c);}global $wpdb;$ids=array();$identity=0;
try{$now=gmdate('Y-m-d H:i:s');$token=wp_generate_uuid4();$mine_key='M3M-'.$token;$other_key='M3O-'.$token;$past_key='M3P-'.$token;$wpdb->insert($wpdb->prefix.'atlas_shipping_identities',array('email'=>'m003-'.$token.'@example.test','full_name'=>'M003 Coverage '.$token,'role'=>'Project Manager','enabled'=>1,'created_at'=>$now,'updated_at'=>$now));$identity=absint($wpdb->insert_id);m3check($identity,'identity-create');$s=new Service();
 $mine=$s->create_draft(array('project_id'=>$mine_key,'project_name'=>'Searchable '.$token),1);$other=$s->create_draft(array('project_id'=>$other_key,'project_name'=>'Coverage '.$token),$identity);$past=$s->create_draft(array('project_id'=>$past_key,'project_name'=>'Past '.$token),1);foreach(array($mine,$other,$past)as$r){m3check(!is_wp_error($r),'draft-create');$ids[]=$r->id();}$wpdb->update($wpdb->prefix.'atlas_shipping_requests',array('requested_ship_date'=>gmdate('Y-m-d',time()+86400)),array('id'=>$mine->id()));$wpdb->update($wpdb->prefix.'atlas_shipping_requests',array('required_delivery_date'=>gmdate('Y-m-d',time()+172800)),array('id'=>$other->id()));$wpdb->update($wpdb->prefix.'atlas_shipping_requests',array('required_delivery_date'=>gmdate('Y-m-d',time()-86400)),array('id'=>$past->id()));
 $mine_list=$s->list_requests(array('view'=>'upcoming','page'=>1,'per_page'=>25),1,true);m3check(1===count(array_filter($mine_list['rows'],fn($r)=>$mine_key===$r['project_id']))&&0===count(array_filter($mine_list['rows'],fn($r)=>$other_key===$r['project_id'])),'mine-scope');
 $all=$s->list_requests(array('view'=>'upcoming','page'=>1,'per_page'=>1,'sort'=>'owner','direction'=>'asc'),1,false);m3check($all['total']>=2&&1===count($all['rows'])&&$all['pages']>=2,'all-pagination');
 $owner=$s->list_requests(array('view'=>'upcoming','owner'=>$identity,'page'=>1,'per_page'=>25),1,false);m3check(1===count(array_filter($owner['rows'],fn($r)=>$other_key===$r['project_id'])),'owner-filter');
 $search=$s->list_requests(array('view'=>'upcoming','search'=>$token,'sort'=>'DROP TABLE requests','page'=>1,'per_page'=>25),1,false);m3check(count($search['rows'])>=2,'search-or-sort-whitelist');
 $past_list=$s->list_requests(array('view'=>'past','page'=>1,'per_page'=>25),1,false);m3check(1===count(array_filter($past_list['rows'],fn($r)=>$past_key===$r['project_id'])),'past-filter');
 $detail=$s->view_request($other->get('public_id'),1);m3check(!is_wp_error($detail)&&$identity===absint($detail->get('owner_identity_id')),'cross-user-detail');$blocked=$s->load_for_owner($other->get('public_id'),1);m3check(is_wp_error($blocked)&&'atlas_request_forbidden'===$blocked->get_error_code(),'cross-user-edit-blocked');
 echo wp_json_encode(array('result'=>'passed','checks'=>array('mine_owner_scope','all_cross_identity','pagination_totals','owner_filter','search','sort_whitelist','past_temporal_filter','cross_user_detail','cross_user_edit_blocked')),JSON_PRETTY_PRINT).PHP_EOL;
}catch(Throwable $e){fwrite(STDERR,wp_json_encode(array('result'=>'failed','error'=>$e->getMessage())).PHP_EOL);exit(1);}finally{foreach($ids as$id){$wpdb->delete($wpdb->prefix.'atlas_shipping_activity',array('object_type'=>'shipping_request','object_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_requests',array('id'=>$id));}if($identity)$wpdb->delete($wpdb->prefix.'atlas_shipping_identities',array('id'=>$identity));}
