<?php
require 'C:/Users/govin/Local Sites/atlas/app/public/wp-load.php';
use AtlasShipping\EditorApi;use AtlasShipping\Sessions;
function rcheck($v,$code){if(!$v)throw new RuntimeException($code);} global $wpdb;
$raw=bin2hex(random_bytes(32));$session_table=$wpdb->prefix.'atlas_shipping_sessions';$request_table=$wpdb->prefix.'atlas_shipping_requests';$ids=array();
try{
 $wpdb->insert($session_table,array('identity_id'=>1,'session_token_hash'=>hash('sha256',$raw),'created_at'=>gmdate('Y-m-d H:i:s'),'expires_at'=>gmdate('Y-m-d H:i:s',time()+3600),'last_activity_at'=>gmdate('Y-m-d H:i:s'),'ip'=>'127.0.0.1','user_agent'=>'ATLAS M002 review harness'));$session_id=$wpdb->insert_id;$_COOKIE[Sessions::COOKIE]=$raw;$api=new EditorApi();
 $call=function($payload)use($api){$r=new WP_REST_Request('POST','/atlas-shipping/v1/draft');$r->set_body(wp_json_encode($payload));$r->set_header('Content-Type','application/json');return$api->create($r);};
 $blank=$call(array('request'=>array(),'stops'=>array(array('sequence_no'=>1,'stop_type'=>'pickup'),array('sequence_no'=>2,'stop_type'=>'delivery')),'items'=>array(array('sequence_no'=>1,'quantity'=>1,'description'=>''))));rcheck(is_wp_error($blank)&&'atlas_draft_not_meaningful'===$blank->get_error_code(),'blank-shell-created-draft');
 $stop=$call(array('request'=>array(),'stops'=>array(array('sequence_no'=>1,'stop_type'=>'pickup','address_line_1'=>'R1-'.wp_generate_uuid4()),array('sequence_no'=>2,'stop_type'=>'delivery')),'items'=>array(array('sequence_no'=>1,'quantity'=>1,'description'=>''))));$sd=$stop->get_data()['request'];$ids[]=absint($sd['id']);rcheck(2===count($sd['stops'])&&!empty($sd['stops'][0]['address_line_1']),'stop-first-input-failed');
 $item=$call(array('request'=>array(),'stops'=>array(array('sequence_no'=>1,'stop_type'=>'pickup'),array('sequence_no'=>2,'stop_type'=>'delivery')),'items'=>array(array('sequence_no'=>1,'quantity'=>1,'description'=>'R1 item '.wp_generate_uuid4()))));$id=$item->get_data()['request'];$ids[]=absint($id['id']);rcheck(1===count($id['items'])&&!empty($id['items'][0]['description']),'item-first-input-failed');
 echo wp_json_encode(array('result'=>'passed','checks'=>array('blank_shell_no_draft','stop_first_input_atomic','item_first_input_atomic','session_owner_derived')),JSON_PRETTY_PRINT).PHP_EOL;
}catch(Throwable $e){fwrite(STDERR,wp_json_encode(array('result'=>'failed','error'=>$e->getMessage())).PHP_EOL);exit(1);}finally{foreach($ids as$id){$wpdb->delete($wpdb->prefix.'atlas_shipping_stops',array('request_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_items',array('request_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_activity',array('object_type'=>'shipping_request','object_id'=>$id));$wpdb->delete($request_table,array('id'=>$id));}if(!empty($session_id))$wpdb->delete($session_table,array('id'=>$session_id));unset($_COOKIE[Sessions::COOKIE]);}
