<?php
require 'C:/Users/govin/Local Sites/atlas/app/public/wp-load.php';
use AtlasShipping\Shipping\Service;
function acheck($v,$code){if(!$v)throw new RuntimeException($code);}global $wpdb;$id=0;
try{$s=new Service();$r=$s->create_draft(array('project_id'=>'R3A-'.wp_generate_uuid4()),1);acheck(!is_wp_error($r),'draft-create');$id=$r->id();$v=absint($r->get('row_version'));$updated=$r->get('updated_at');
 $bad=$s->editor_child_create($id,'stops',array('sequence_no'=>1,'stop_type'=>'bad'),1,$v);$after=$s->load($id);acheck(is_wp_error($bad)&&$v===absint($after->get('row_version'))&&$updated===$after->get('updated_at')&&!$after->stops,'invalid-stop-not-atomic');
 $good=$s->editor_child_create($id,'stops',array('sequence_no'=>1,'stop_type'=>'pickup','site_name'=>'Atomic'),1,$v);acheck(!is_wp_error($good)&&$v+1===absint($good->get('row_version'))&&1===count($good->stops),'valid-stop-version');$v=absint($good->get('row_version'));$stop=$good->stops[0];
 $stale=$s->editor_child_update($id,'stops',$stop->id(),array('sequence_no'=>1,'stop_type'=>'pickup','site_name'=>'Stale'),1,$v-1);$after=$s->load($id);acheck(is_wp_error($stale)&&'atlas_request_conflict'===$stale->get_error_code()&&$v===absint($after->get('row_version'))&&'Atomic'===$after->stops[0]->get('site_name'),'stale-stop-mutated');
 $item=$s->editor_child_create($id,'items',array('sequence_no'=>1,'quantity'=>1,'description'=>'Atomic item'),1,$v);acheck(!is_wp_error($item)&&$v+1===absint($item->get('row_version'))&&1===count($item->items),'valid-item-version');$v=absint($item->get('row_version'));$item_id=$item->items[0]->id();
 $bad_item=$s->editor_child_update($id,'items',$item_id,array('sequence_no'=>1,'quantity'=>0,'description'=>'Invalid'),1,$v);$after=$s->load($id);acheck(is_wp_error($bad_item)&&$v===absint($after->get('row_version'))&&'Atomic item'===$after->items[0]->get('description'),'invalid-item-not-atomic');
 echo wp_json_encode(array('result'=>'passed','checks'=>array('invalid_stop_no_parent_advance','valid_stop_advances_once','stale_stop_mutates_nothing','valid_item_advances_once','invalid_item_no_parent_advance')),JSON_PRETTY_PRINT).PHP_EOL;
}catch(Throwable $e){fwrite(STDERR,wp_json_encode(array('result'=>'failed','error'=>$e->getMessage())).PHP_EOL);exit(1);}finally{if($id){$wpdb->delete($wpdb->prefix.'atlas_shipping_stops',array('request_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_items',array('request_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_activity',array('object_type'=>'shipping_request','object_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_requests',array('id'=>$id));}}
