<?php
require 'C:/Users/govin/Local Sites/atlas/app/public/wp-load.php';
if(!class_exists('AtlasShipping\\Shipping\\Service'))require 'C:/Users/govin/Local Sites/atlas/app/public/wp-content/plugins/atlas-shipping/atlas-shipping.php';
use AtlasShipping\Shipping\Service;
function m006_ok($v,$n){if(!$v)throw new RuntimeException($n);}global $wpdb;$identities=array();$requests=array();
try{
 (new AtlasShipping\Migrator())->run();$token=wp_generate_uuid4();$now=gmdate('Y-m-d H:i:s');
 foreach(array('Project Manager','Shipping Coordinator')as$role){$wpdb->insert($wpdb->prefix.'atlas_shipping_identities',array('email'=>sanitize_key($role).'-'.$token.'@example.test','full_name'=>'M006 '.$role,'role'=>$role,'enabled'=>1,'created_at'=>$now,'updated_at'=>$now));$identities[$role]=absint($wpdb->insert_id);}
 $s=new Service();$pm=$identities['Project Manager'];$co=$identities['Shipping Coordinator'];
 $draft=$s->create_draft(array('project_id'=>'M006-'.$token,'project_name'=>'Response validation','requested_ship_date'=>'2026-10-01'),$pm,array(array('sequence_no'=>1,'stop_type'=>'pickup','site_name'=>'Origin','address_line_1'=>'1 A St','city'=>'Chicago','region'=>'IL','postal_code'=>'60601'),array('sequence_no'=>2,'stop_type'=>'delivery','site_name'=>'Destination','address_line_1'=>'2 B St','city'=>'Madison','region'=>'WI','postal_code'=>'53703')),array(array('sequence_no'=>1,'quantity'=>1,'description'=>'Crate')));m006_ok(!is_wp_error($draft),'draft');$requests[]=$draft->id();
 $submitted=$s->submit($draft->id(),$pm,$draft->get('row_version'));$sent=$s->send_handoff($submitted->get('public_id'),array('final_equipment'=>'box_truck','load_pickup'=>1),$co,$submitted->get('row_version'));m006_ok(!is_wp_error($sent),'handoff');
 $partial=array('carrier_name'=>'Atlas Carrier','actual_equipment'=>'other','other_equipment'=>'Liftgate truck','contact_name'=>'Driver One','contact_phone'=>'555-0100','contact_email'=>'driver@example.test','pickup_window_start'=>'2026-10-01 14:00:00','delivery_window_start'=>'2026-10-02 15:00:00','freight_cost'=>'0','currency'=>'USD','reference_number'=>'LOAD-1','coordinator_notes'=>'Manual response');
 m006_ok(is_wp_error($s->save_response($sent->get('public_id'),$partial,$pm,$sent->get('row_version'))),'pm-mutation-blocked');
 $saved=$s->save_response($sent->get('public_id'),$partial,$co,$sent->get('row_version'));m006_ok(!is_wp_error($saved)&&'sent_to_shipper'===$saved->get('status'),'partial-no-transition');m006_ok($saved->actual_details['freight_cost']==='0.00'&&!$saved->actual_details['freight_cost_pending'],'zero-distinct');m006_ok($saved->get('preferred_equipment')!==$saved->actual_details['actual_equipment']&&$saved->handoff['final_equipment']!==$saved->actual_details['actual_equipment'],'three-concepts');
 m006_ok(is_wp_error($s->confirm_response($sent->get('public_id'),$partial,$co,$sent->get('row_version'))),'stale-blocked');
 $confirmed=$s->confirm_response($saved->get('public_id'),$partial,$co,$saved->get('row_version'));m006_ok(!is_wp_error($confirmed)&&'scheduled'===$confirmed->get('status')&&!empty($confirmed->get('scheduled_at'))&&!empty($confirmed->actual_details['confirmed_at']),'scheduled');m006_ok(is_wp_error($s->confirm_response($confirmed->get('public_id'),$partial,$co,$confirmed->get('row_version'))),'duplicate-blocked');
 $queue=$s->coordinator_queue($co);m006_ok(!array_filter($queue['rows'],fn($r)=>$r['public_id']===$confirmed->get('public_id')),'queue-cleared');
 echo wp_json_encode(array('result'=>'passed','checks'=>array('migration_008','pm_mutation_forbidden','partial_save','distinct_models','carrier_equipment_contact_schedule','zero_cost_distinct','stale_rejected','atomic_scheduled_transition','timestamp','duplicate_rejected','queue_cleared')),JSON_PRETTY_PRINT).PHP_EOL;
}catch(Throwable $e){fwrite(STDERR,wp_json_encode(array('result'=>'failed','error'=>$e->getMessage())).PHP_EOL);exit(1);}finally{foreach($requests as$id){foreach(array('activity','snapshots','handoffs','shipper_responses','stops','items')as$t)$wpdb->delete($wpdb->prefix.'atlas_shipping_'.$t,'activity'===$t?array('object_type'=>'shipping_request','object_id'=>$id):array('request_id'=>$id));$wpdb->delete($wpdb->prefix.'atlas_shipping_requests',array('id'=>$id));}foreach($identities as$id)$wpdb->delete($wpdb->prefix.'atlas_shipping_identities',array('id'=>$id));}
