[CmdletBinding()]
param([string]$RepositoryRoot='',[switch]$NoExitFailure)
$ErrorActionPreference='Stop';if(-not$RepositoryRoot){$RepositoryRoot=Split-Path -Parent $PSScriptRoot};$RepositoryRoot=(Resolve-Path $RepositoryRoot).Path;$fail=[Collections.Generic.List[string]]::new()
foreach($file in @('framework.json','framework.lock','repository.operations.json','workflow-state.json')){if(-not(Test-Path(Join-Path $RepositoryRoot $file))){$fail.Add("installed-authority-missing:$file")}}
foreach($file in @('framework.json','repository.operations.json','workflow-state.json')){try{Get-Content -Raw (Join-Path $RepositoryRoot $file)|ConvertFrom-Json|Out-Null}catch{$fail.Add("installed-authority-invalid:$file")}}
$frameworkPath=Join-Path $RepositoryRoot 'framework.json';$workflowPath=Join-Path $RepositoryRoot 'workflow-state.json';if((Test-Path $frameworkPath)-and(Test-Path $workflowPath)){try{$framework=Get-Content -Raw $frameworkPath|ConvertFrom-Json;$workflow=Get-Content -Raw $workflowPath|ConvertFrom-Json;$productLine=if([string]$workflow.current_build-match'^(.+)-dev\.\d+$'){$Matches[1]}else{$null};if($productLine-and[string]$workflow.release_target-ne$productLine){$fail.Add('product-release-target-build-mismatch')};if($productLine-and[string]$workflow.release_target-eq[string]$framework.release_target-and$productLine-ne[string]$framework.release_target){$fail.Add('product-release-target-framework-identity-conflict')}}catch{}}
if($workflow-and[string]$workflow.next_command-eq'Implement Milestone'){if([string]$workflow.current_status-ne'active'){$fail.Add('implement-milestone-requires-active-status')};if([string]::IsNullOrWhiteSpace([string]$workflow.current_milestone)){$fail.Add('implement-milestone-requires-current-milestone')}}
$schema=Join-Path $RepositoryRoot 'schemas-integrity/workflow-state-schema.json';if(-not(Test-Path $schema)){$schema=Join-Path (Split-Path -Parent $PSScriptRoot) 'installed-workflow-state-schema.json'};if(Test-Path $schema){$raw=& (Join-Path $PSScriptRoot 'test-json-schema-instance.ps1') -SchemaPath $schema -InstancePath (Join-Path $RepositoryRoot 'workflow-state.json') -NoExitFailure;$checked=$raw|ConvertFrom-Json;if($checked.result-ne'passed'){$fail.Add('installed-workflow-schema-invalid')}}else{$fail.Add('installed-workflow-schema-missing')}
if(Test-Path(Join-Path $RepositoryRoot 'repository.operations.json')){$ops=Get-Content -Raw (Join-Path $RepositoryRoot 'repository.operations.json')|ConvertFrom-Json;foreach($property in $ops.operations.PSObject.Properties){$op=$property.Value;if($op.applicability-eq'required'){$command=[string]$op.command;if($command-notmatch'^\./scripts/[A-Za-z0-9._-]+\.ps1$'-or-not(Test-Path(Join-Path $RepositoryRoot $command.Substring(2)))){$fail.Add("required-operation-missing:$($property.Name)")}}}}
foreach($lock in @(Get-ChildItem (Join-Path $RepositoryRoot 'docs/extensions') -Filter '*.lock' -File -ErrorAction SilentlyContinue)){if((Get-Content -Raw $lock.FullName)-notmatch'(?m)^extension-(?:slug|id):'){$fail.Add("extension-lock-invalid:$($lock.Name)")}}
$result=[ordered]@{schema_version=1;result=$(if($fail.Count){'failed'}else{'passed'});failures=@($fail)};$result|ConvertTo-Json -Depth 8;if($fail.Count-and-not$NoExitFailure){exit 1}
